# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlTowerUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        self.plotter = GraphWidget(Dialog)
        self.plotter.setGeometry(QtCore.QRect(810, 0, 771, 441))
        self.plotter.setObjectName("plotter")
        self.laps_left = QtWidgets.QTableWidget(Dialog)
        self.laps_left.setGeometry(QtCore.QRect(1230, 550, 351, 61))
        self.laps_left.setMaximumSize(QtCore.QSize(530, 61))
        self.laps_left.setStyleSheet("")
        self.laps_left.setObjectName("laps_left")
        self.laps_left.setColumnCount(2)
        self.laps_left.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.laps_left.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laps_left.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laps_left.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laps_left.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laps_left.setItem(0, 1, item)
        self.laps_left.horizontalHeader().setVisible(False)
        self.laps_left.horizontalHeader().setDefaultSectionSize(170)
        self.laps_left.verticalHeader().setVisible(False)
        self.laps_left.verticalHeader().setDefaultSectionSize(58)
        self.laps_left.verticalHeader().setHighlightSections(True)
        self.total_time = QtWidgets.QTableWidget(Dialog)
        self.total_time.setGeometry(QtCore.QRect(1230, 480, 351, 61))
        self.total_time.setMaximumSize(QtCore.QSize(530, 61))
        self.total_time.setStyleSheet("")
        self.total_time.setObjectName("total_time")
        self.total_time.setColumnCount(2)
        self.total_time.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.total_time.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.total_time.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.total_time.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.total_time.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.total_time.setItem(0, 1, item)
        self.total_time.horizontalHeader().setVisible(False)
        self.total_time.horizontalHeader().setDefaultSectionSize(170)
        self.total_time.verticalHeader().setVisible(False)
        self.total_time.verticalHeader().setDefaultSectionSize(58)
        self.total_time.verticalHeader().setHighlightSections(True)
        self.choose_item = QtWidgets.QComboBox(Dialog)
        self.choose_item.setGeometry(QtCore.QRect(1480, 450, 101, 25))
        self.choose_item.setEditable(False)
        self.choose_item.setObjectName("choose_item")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.velocity_table = QtWidgets.QTableWidget(Dialog)
        self.velocity_table.setGeometry(QtCore.QRect(810, 450, 411, 191))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.velocity_table.setFont(font)
        self.velocity_table.setShowGrid(True)
        self.velocity_table.setObjectName("velocity_table")
        self.velocity_table.setColumnCount(2)
        self.velocity_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(4, 1, item)
        self.velocity_table.horizontalHeader().setVisible(False)
        self.velocity_table.horizontalHeader().setCascadingSectionResizes(True)
        self.velocity_table.horizontalHeader().setDefaultSectionSize(200)
        self.velocity_table.verticalHeader().setVisible(False)
        self.velocity_table.verticalHeader().setCascadingSectionResizes(True)
        self.velocity_table.verticalHeader().setDefaultSectionSize(36)
        self.lap_count = QtWidgets.QTableWidget(Dialog)
        self.lap_count.setGeometry(QtCore.QRect(1230, 620, 351, 61))
        self.lap_count.setMaximumSize(QtCore.QSize(530, 61))
        self.lap_count.setStyleSheet("")
        self.lap_count.setObjectName("lap_count")
        self.lap_count.setColumnCount(2)
        self.lap_count.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.lap_count.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lap_count.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lap_count.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.lap_count.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.lap_count.setItem(0, 1, item)
        self.lap_count.horizontalHeader().setVisible(False)
        self.lap_count.horizontalHeader().setDefaultSectionSize(170)
        self.lap_count.verticalHeader().setVisible(False)
        self.lap_count.verticalHeader().setDefaultSectionSize(58)
        self.lap_count.verticalHeader().setHighlightSections(True)
        self.torque_table = QtWidgets.QTableWidget(Dialog)
        self.torque_table.setGeometry(QtCore.QRect(1230, 700, 351, 151))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.torque_table.setFont(font)
        self.torque_table.setObjectName("torque_table")
        self.torque_table.setColumnCount(2)
        self.torque_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(3, 1, item)
        self.torque_table.horizontalHeader().setVisible(False)
        self.torque_table.horizontalHeader().setDefaultSectionSize(170)
        self.torque_table.verticalHeader().setVisible(False)
        self.torque_table.verticalHeader().setDefaultSectionSize(37)
        self.laptimerlap = QtWidgets.QTableWidget(Dialog)
        self.laptimerlap.setGeometry(QtCore.QRect(810, 650, 401, 231))
        self.laptimerlap.setObjectName("laptimerlap")
        self.laptimerlap.setColumnCount(2)
        self.laptimerlap.setRowCount(11)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(10, 0, item)
        self.laptimerlap.horizontalHeader().setDefaultSectionSize(180)
        self.laptimerlap.verticalHeader().setVisible(False)
        self.laptimerlap.verticalHeader().setDefaultSectionSize(30)
        self.laptimerlap.verticalHeader().setHighlightSections(False)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.laps_left.isSortingEnabled()
        self.laps_left.setSortingEnabled(False)
        item = self.laps_left.item(0, 0)
        item.setText(_translate("Dialog", "남은 랩수"))
        self.laps_left.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.total_time.isSortingEnabled()
        self.total_time.setSortingEnabled(False)
        item = self.total_time.item(0, 0)
        item.setText(_translate("Dialog", "총 주행 시간"))
        self.total_time.setSortingEnabled(__sortingEnabled)
        self.choose_item.setItemText(0, _translate("Dialog", "그래프 출력"))
        self.choose_item.setItemText(1, _translate("Dialog", "쓰로틀"))
        self.choose_item.setItemText(2, _translate("Dialog", "FL 토크"))
        self.choose_item.setItemText(3, _translate("Dialog", "FR 토크"))
        self.choose_item.setItemText(4, _translate("Dialog", "RL 토크"))
        self.choose_item.setItemText(5, _translate("Dialog", "RR 토크"))
        self.choose_item.setItemText(6, _translate("Dialog", "차량 속도"))
        self.choose_item.setItemText(7, _translate("Dialog", "FL 속도"))
        self.choose_item.setItemText(8, _translate("Dialog", "FR 속도"))
        self.choose_item.setItemText(9, _translate("Dialog", "RL 속도"))
        self.choose_item.setItemText(10, _translate("Dialog", "RR 속도"))
        self.choose_item.setItemText(11, _translate("Dialog", "Clear"))
        __sortingEnabled = self.velocity_table.isSortingEnabled()
        self.velocity_table.setSortingEnabled(False)
        item = self.velocity_table.item(0, 0)
        item.setText(_translate("Dialog", "현재속도"))
        item = self.velocity_table.item(1, 0)
        item.setText(_translate("Dialog", "FL 속도"))
        item = self.velocity_table.item(2, 0)
        item.setText(_translate("Dialog", "FR 속도"))
        item = self.velocity_table.item(3, 0)
        item.setText(_translate("Dialog", "RL 속도"))
        item = self.velocity_table.item(4, 0)
        item.setText(_translate("Dialog", "RR 속도"))
        self.velocity_table.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lap_count.isSortingEnabled()
        self.lap_count.setSortingEnabled(False)
        item = self.lap_count.item(0, 0)
        item.setText(_translate("Dialog", "현재 랩수"))
        self.lap_count.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.torque_table.isSortingEnabled()
        self.torque_table.setSortingEnabled(False)
        item = self.torque_table.item(0, 0)
        item.setText(_translate("Dialog", "FL 토크"))
        item = self.torque_table.item(1, 0)
        item.setText(_translate("Dialog", "FR 토크"))
        item = self.torque_table.item(2, 0)
        item.setText(_translate("Dialog", "RL 토크"))
        item = self.torque_table.item(3, 0)
        item.setText(_translate("Dialog", "RR 토크"))
        self.torque_table.setSortingEnabled(__sortingEnabled)
        item = self.laptimerlap.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "랩 수"))
        item = self.laptimerlap.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "랩 타임"))
        __sortingEnabled = self.laptimerlap.isSortingEnabled()
        self.laptimerlap.setSortingEnabled(False)
        self.laptimerlap.setSortingEnabled(__sortingEnabled)
from graphWidget import GraphWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
