# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'controlTowerUi.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1600, 900)
        self.plotter = GraphWidget(Dialog)
        self.plotter.setGeometry(QtCore.QRect(810, 0, 771, 441))
        self.plotter.setObjectName("plotter")
        self.laps_left_table = QtWidgets.QTableWidget(Dialog)
        self.laps_left_table.setGeometry(QtCore.QRect(1230, 550, 351, 61))
        self.laps_left_table.setMaximumSize(QtCore.QSize(530, 61))
        self.laps_left_table.setStyleSheet("")
        self.laps_left_table.setObjectName("laps_left_table")
        self.laps_left_table.setColumnCount(2)
        self.laps_left_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.laps_left_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laps_left_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laps_left_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laps_left_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laps_left_table.setItem(0, 1, item)
        self.laps_left_table.horizontalHeader().setVisible(False)
        self.laps_left_table.horizontalHeader().setDefaultSectionSize(170)
        self.laps_left_table.verticalHeader().setVisible(False)
        self.laps_left_table.verticalHeader().setDefaultSectionSize(58)
        self.laps_left_table.verticalHeader().setHighlightSections(True)
        self.total_time_table = QtWidgets.QTableWidget(Dialog)
        self.total_time_table.setGeometry(QtCore.QRect(1230, 480, 351, 61))
        self.total_time_table.setMaximumSize(QtCore.QSize(530, 61))
        self.total_time_table.setStyleSheet("")
        self.total_time_table.setObjectName("total_time_table")
        self.total_time_table.setColumnCount(2)
        self.total_time_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.total_time_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.total_time_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.total_time_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.total_time_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.total_time_table.setItem(0, 1, item)
        self.total_time_table.horizontalHeader().setVisible(False)
        self.total_time_table.horizontalHeader().setDefaultSectionSize(170)
        self.total_time_table.verticalHeader().setVisible(False)
        self.total_time_table.verticalHeader().setDefaultSectionSize(58)
        self.total_time_table.verticalHeader().setHighlightSections(True)
        self.choose_item = QtWidgets.QComboBox(Dialog)
        self.choose_item.setGeometry(QtCore.QRect(1480, 450, 101, 25))
        self.choose_item.setEditable(False)
        self.choose_item.setObjectName("choose_item")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.choose_item.addItem("")
        self.velocity_table = QtWidgets.QTableWidget(Dialog)
        self.velocity_table.setGeometry(QtCore.QRect(810, 450, 411, 191))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.velocity_table.setFont(font)
        self.velocity_table.setShowGrid(True)
        self.velocity_table.setObjectName("velocity_table")
        self.velocity_table.setColumnCount(2)
        self.velocity_table.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.velocity_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.velocity_table.setItem(4, 1, item)
        self.velocity_table.horizontalHeader().setVisible(False)
        self.velocity_table.horizontalHeader().setCascadingSectionResizes(True)
        self.velocity_table.horizontalHeader().setDefaultSectionSize(200)
        self.velocity_table.verticalHeader().setVisible(False)
        self.velocity_table.verticalHeader().setCascadingSectionResizes(True)
        self.velocity_table.verticalHeader().setDefaultSectionSize(36)
        self.lap_count_table = QtWidgets.QTableWidget(Dialog)
        self.lap_count_table.setGeometry(QtCore.QRect(1230, 620, 351, 61))
        self.lap_count_table.setMaximumSize(QtCore.QSize(530, 61))
        self.lap_count_table.setStyleSheet("")
        self.lap_count_table.setObjectName("lap_count_table")
        self.lap_count_table.setColumnCount(2)
        self.lap_count_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.lap_count_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lap_count_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.lap_count_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.lap_count_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.lap_count_table.setItem(0, 1, item)
        self.lap_count_table.horizontalHeader().setVisible(False)
        self.lap_count_table.horizontalHeader().setDefaultSectionSize(170)
        self.lap_count_table.verticalHeader().setVisible(False)
        self.lap_count_table.verticalHeader().setDefaultSectionSize(58)
        self.lap_count_table.verticalHeader().setHighlightSections(True)
        self.torque_table = QtWidgets.QTableWidget(Dialog)
        self.torque_table.setGeometry(QtCore.QRect(1230, 700, 351, 151))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.torque_table.setFont(font)
        self.torque_table.setObjectName("torque_table")
        self.torque_table.setColumnCount(2)
        self.torque_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.torque_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.torque_table.setItem(3, 1, item)
        self.torque_table.horizontalHeader().setVisible(False)
        self.torque_table.horizontalHeader().setDefaultSectionSize(170)
        self.torque_table.verticalHeader().setVisible(False)
        self.torque_table.verticalHeader().setDefaultSectionSize(37)
        self.laptimerlap = QtWidgets.QTableWidget(Dialog)
        self.laptimerlap.setGeometry(QtCore.QRect(810, 650, 401, 231))
        self.laptimerlap.setObjectName("laptimerlap")
        self.laptimerlap.setColumnCount(2)
        self.laptimerlap.setRowCount(30)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(25, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(26, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(27, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(28, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setVerticalHeaderItem(29, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.laptimerlap.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(8, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(9, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(10, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(11, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(12, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(13, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(14, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(15, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(16, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(17, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(18, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(19, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(20, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(21, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(22, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(23, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(24, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(25, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(26, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(27, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(28, 1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.laptimerlap.setItem(29, 1, item)
        self.laptimerlap.horizontalHeader().setDefaultSectionSize(180)
        self.laptimerlap.verticalHeader().setVisible(False)
        self.laptimerlap.verticalHeader().setDefaultSectionSize(30)
        self.laptimerlap.verticalHeader().setHighlightSections(False)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        __sortingEnabled = self.laps_left_table.isSortingEnabled()
        self.laps_left_table.setSortingEnabled(False)
        item = self.laps_left_table.item(0, 0)
        item.setText(_translate("Dialog", "남은 랩수"))
        item = self.laps_left_table.item(0, 1)
        item.setText(_translate("Dialog", "7"))
        self.laps_left_table.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.total_time_table.isSortingEnabled()
        self.total_time_table.setSortingEnabled(False)
        item = self.total_time_table.item(0, 0)
        item.setText(_translate("Dialog", "총 주행 시간"))
        item = self.total_time_table.item(0, 1)
        item.setText(_translate("Dialog", "6"))
        self.total_time_table.setSortingEnabled(__sortingEnabled)
        self.choose_item.setItemText(0, _translate("Dialog", "그래프 출력"))
        self.choose_item.setItemText(1, _translate("Dialog", "쓰로틀"))
        self.choose_item.setItemText(2, _translate("Dialog", "FL 토크"))
        self.choose_item.setItemText(3, _translate("Dialog", "FR 토크"))
        self.choose_item.setItemText(4, _translate("Dialog", "RL 토크"))
        self.choose_item.setItemText(5, _translate("Dialog", "RR 토크"))
        self.choose_item.setItemText(6, _translate("Dialog", "차량 속도"))
        self.choose_item.setItemText(7, _translate("Dialog", "FL 속도"))
        self.choose_item.setItemText(8, _translate("Dialog", "FR 속도"))
        self.choose_item.setItemText(9, _translate("Dialog", "RL 속도"))
        self.choose_item.setItemText(10, _translate("Dialog", "RR 속도"))
        self.choose_item.setItemText(11, _translate("Dialog", "Clear"))
        __sortingEnabled = self.velocity_table.isSortingEnabled()
        self.velocity_table.setSortingEnabled(False)
        item = self.velocity_table.item(0, 0)
        item.setText(_translate("Dialog", "현재속도"))
        item = self.velocity_table.item(0, 1)
        item.setText(_translate("Dialog", "1"))
        item = self.velocity_table.item(1, 0)
        item.setText(_translate("Dialog", "FL 속도"))
        item = self.velocity_table.item(1, 1)
        item.setText(_translate("Dialog", "2"))
        item = self.velocity_table.item(2, 0)
        item.setText(_translate("Dialog", "FR 속도"))
        item = self.velocity_table.item(2, 1)
        item.setText(_translate("Dialog", "3"))
        item = self.velocity_table.item(3, 0)
        item.setText(_translate("Dialog", "RL 속도"))
        item = self.velocity_table.item(3, 1)
        item.setText(_translate("Dialog", "4"))
        item = self.velocity_table.item(4, 0)
        item.setText(_translate("Dialog", "RR 속도"))
        item = self.velocity_table.item(4, 1)
        item.setText(_translate("Dialog", "5"))
        self.velocity_table.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.lap_count_table.isSortingEnabled()
        self.lap_count_table.setSortingEnabled(False)
        item = self.lap_count_table.item(0, 0)
        item.setText(_translate("Dialog", "현재 랩수"))
        item = self.lap_count_table.item(0, 1)
        item.setText(_translate("Dialog", "8"))
        self.lap_count_table.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.torque_table.isSortingEnabled()
        self.torque_table.setSortingEnabled(False)
        item = self.torque_table.item(0, 0)
        item.setText(_translate("Dialog", "FL 토크"))
        item = self.torque_table.item(0, 1)
        item.setText(_translate("Dialog", "9"))
        item = self.torque_table.item(1, 0)
        item.setText(_translate("Dialog", "FR 토크"))
        item = self.torque_table.item(1, 1)
        item.setText(_translate("Dialog", "10"))
        item = self.torque_table.item(2, 0)
        item.setText(_translate("Dialog", "RL 토크"))
        item = self.torque_table.item(2, 1)
        item.setText(_translate("Dialog", "11"))
        item = self.torque_table.item(3, 0)
        item.setText(_translate("Dialog", "RR 토크"))
        item = self.torque_table.item(3, 1)
        item.setText(_translate("Dialog", "12"))
        self.torque_table.setSortingEnabled(__sortingEnabled)
        item = self.laptimerlap.verticalHeaderItem(0)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(1)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(2)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(3)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(4)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(5)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(6)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(7)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(8)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(9)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(10)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(11)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(12)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(13)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(14)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(15)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(16)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(17)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(18)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(19)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(20)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(21)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(22)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(23)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(24)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(25)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(26)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(27)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(28)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.verticalHeaderItem(29)
        item.setText(_translate("Dialog", "New Row"))
        item = self.laptimerlap.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "랩 수"))
        item = self.laptimerlap.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "랩 타임"))
        __sortingEnabled = self.laptimerlap.isSortingEnabled()
        self.laptimerlap.setSortingEnabled(False)
        item = self.laptimerlap.item(0, 0)
        item.setText(_translate("Dialog", "1"))
        item = self.laptimerlap.item(0, 1)
        item.setText(_translate("Dialog", "2"))
        self.laptimerlap.setSortingEnabled(__sortingEnabled)
from graphWidget import GraphWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
